Ey 1775 bruke pensjon etterlatte lib
navikt/pensjon-etterlatte-saksbehandling pull request #1127
Opened 2023-03-28 12:45 UTC by Bjodn

2023-03-28 15:43 UTC, henrikg approved these changes

2023-03-28 15:43 UTC, henrikg commented on libs/etterlatte-database/build.gradle.kts
> +    maven {
Må vi ta inn dette overalt hvor common nå brukes?

2023-03-29 05:45 UTC, madsop-nav commented on apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevModel.kt
> +enum class Spraak(@get:JsonValue val verdi: String) { NB("nb"), NN("nn"), EN("en") }
💯

2023-03-29 05:48 UTC, madsop-nav commented on buildSrc/src/main/kotlin/Etterlatte.kt
> +object Etterlatte {
Trur det er lurt å heller leggje denne inn i `libs.versions.toml`, da er vi konsekvente på å gjera imports på samme måte som elles.

2023-03-29 05:49 UTC, madsop-nav commented on libs/etterlatte-database/build.gradle.kts
> +    maven {
Foreløpig, men eg, Bjørn og Nicolas såg litt på det i går, og kom fram til at vi uansett snart skal rydde bort mykje av behovet, så teorien er at desse importane ikkje skal leve så lengje før vi blir kvitt dei igjen.

2023-03-29 05:51 UTC, madsop-nav requested changes
Godt jobba, det her er eit godt steg på vegen mot å få noko markant ryddigare.

Request changes fordi eg gjerne vil ha imports likt som elles, dvs via toml-fila.

2023-03-29 06:37 UTC, Watercolours commented on buildSrc/src/main/kotlin/Etterlatte.kt
> +    const val Common = "no.nav.etterlatte:common:2023.03.28-16.21.c37f68b0da69"
Tenker du da på implementation i gradle eller import i kotlin-filer? 
Det er hvert fall en enkel fiks å gi den et annet navn i gradle. Må litt mer opprydding til for at det skal bli mer forståelig i imports.

2023-03-29 06:38 UTC, Watercolours commented on libs/testdata/src/main/kotlin/soeknad/InnsendtSoeknadTestData.kt
>  object InnsendtSoeknadTestData {
Finnes det ikke testdata for søknad i common test lib?

2023-03-29 06:39 UTC, Watercolours approved these changes
Blir bra dette. Burde ryddes litt mer i sak common, men det kan vi ta fortløpende.

2023-03-29 10:28 UTC, madsop-nav approved these changes

2023-03-29 10:40 UTC, sebassonav approved these changes

2023-04-03 06:40 UTC, henrikg commented on buildSrc/src/main/kotlin/Etterlatte.kt
> +    const val Common = "no.nav.etterlatte:common:2023.03.28-16.21.c37f68b0da69"
Kanskje gradle i første runde med tanke på det du sier om imports

2023-04-03 06:43 UTC, henrikg approved these changes
🚀

2023-04-03 06:43 UTC, henrikg commented on libs/common/src/main/kotlin/behandling/KommerBarnetTilgode.kt
> +enum class JaNeiVetIkke { JA, NEI }
Endre navnet på enumen også?

2023-04-03 09:04 UTC, merged