Fjerne unødvendig wrapper rundt kotliquery
navikt/pensjon-etterlatte-saksbehandling pull request #1157
Opened 2023-03-30 12:46 UTC by Watercolours

2023-03-30 14:27 UTC, sebassonav approved these changes

2023-03-31 06:13 UTC, madsop-nav requested changes
Ref forrige kommentar

2023-03-31 06:29 UTC, Watercolours commented on apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingRepository.kt
> +        using(sessionOf(datasource)) { session ->
Jeg synes det er litt uheldig å lage en wrapper rundt et bibliotek som er en wrapper. Dette gjør det vanskelig å se hva som faktisk skjer. Jeg er enig i at Kotliquery her kan være litt tung å lese, men det blir ikke bedre av å skjule hva som skjer. 

Tenker det er bedre at vi revurderer måten vi har implementert Kotliquery på og/eller undersøker om det finnes bedre og mer lettleste måter å skrive samme kode på, enn at vi bygger noe rundt det.

2023-03-31 06:39 UTC, madsop-nav commented on apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingRepository.kt
> +        using(sessionOf(datasource)) { session ->
Ser poenget, men ser på det meir frå vinkelen om kva det er interessant/nyttig å veta når.

Når eg skal skrive ein update query, vil eg fokusere mest på kva den updaten skal gjera, med funksjonelle briller. Da er eg glad og fornøgd med å kunne bruke ein standard-måte vi har laga oss for update queries, og da held det for meg å veta at denne metoden gjer update.

Å sikre at vi gjer update queries på riktig måte er derimot eit reint teknisk spørsmål, og som eg ser det noko det held at vi gjer éin gong i kodebasen vår, og noko som i grunn er uavhengig av _kva for update_ vi gjer. Da synes eg det er fint å separere det ut, sånn at eg ser kun på den funksjonelle delen når eg er i "funksjonell modus" og kun den tekniske delen når eg er i "teknisk modus".

Men ja, abstraksjonar er jo alltid ein trade-off. Skulle ønskje meg at dette var funksjonalitet kotliquery hadde bygd inn direkte, så vi slapp å wrappe det sjølv, og er absolutt open for at det er betre måtar å løyse det på.

2023-03-31 06:58 UTC, Watercolours commented on apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingRepository.kt
> +        using(sessionOf(datasource)) { session ->
Det ble hvert fall diskutert med flere av oss på kontoret i går at det burde fjernes, men jeg kan godt lage en lapp til utviklersync om du synes det er bedre at vi tar opp diskusjonen i plenum.

2023-03-31 07:05 UTC, madsop-nav commented on apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingRepository.kt
> +        using(sessionOf(datasource)) { session ->
Ja, høyrast ut som ein nyttig diskusjon å ta på utviklarsynk.

2023-04-14 07:31 UTC, closed without merging