EY-1786 - filter behandling på sak
navikt/pensjon-etterlatte-saksbehandling pull request #1252
Opened 2023-04-14 10:04 UTC by chrissearle

2023-04-14 13:39 UTC, madsop-nav commented on apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingDao.kt
> +                    SELECT b.*, s.sakType, s.enhet, s.fnr
Burde vi vurdere eit databaseview her? Kjens som det er ei logisk kopling mellom desse felta som vi per no ikkje representerer ordentleg.

2023-04-14 13:40 UTC, madsop-nav commented on apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingRoutes.kt
> +                null -> call.respond(HttpStatusCode.NotFound)
🎯

2023-04-14 13:44 UTC, madsop-nav commented on apps/etterlatte-behandling/src/main/kotlin/behandling/foerstegangsbehandling/FoerstegangsbehandlingService.kt
> +    fun hentBehandling(id: UUID): Foerstegangsbehandling? =
Mistar vi noko ved å ikkje lenger krevje at denne er non-null?

2023-04-17 05:49 UTC, chrissearle commented on apps/etterlatte-behandling/src/main/kotlin/behandling/foerstegangsbehandling/FoerstegangsbehandlingService.kt
> +    fun hentBehandling(id: UUID): Foerstegangsbehandling? =
At den ikke kaster hvis den ikke er null lenger. Dermed må vi håndtere det alle steder. Men - vi kan ikke lenger garantere at det ikke er null - har du ikke tilgang får du null tilbake. Så det håndtering må skje. Dermed route endringer som sender 404

2023-04-17 07:25 UTC, chrissearle commented on apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingDao.kt
> +                    SELECT b.*, s.sakType, s.enhet, s.fnr
Høres ut som dette tas som eget sak på utviklersync

2023-04-17 09:37 UTC, Watercolours commented on apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingDao.kt
> +        enhet = rs.getString("enhet").takeIf { !rs.wasNull() }
Bruk heller `takeUnless`

2023-04-17 10:05 UTC, Watercolours requested changes
Ikke fan av måten enheter filtreres på. Særlig det at `FeatureToggleService` sendes rundt.

2023-04-17 10:34 UTC, chrissearle commented on apps/etterlatte-behandling/src/main/kotlin/behandling/GenerellBehandlingService.kt
> +    } ?: true
Problem er at logikken i topp nivå filterForEnheter er per nå kronglete i seg selv.

```
fun <T> List<T>.filterForEnheter(
    featureToggleService: FeatureToggleService,
    toggle: FeatureToggle,
    user: User,
    filter: (item: T, enheter: List<String>) -> Boolean
) =
    if (featureToggleService.isEnabled(toggle, false)) {
        when (user) {
            is no.nav.etterlatte.Saksbehandler -> {
                val enheter = user.enheter().map { it.id }

                this.filter { filter(it, enheter) }
            }

            else -> this
        }
    } else {
        this
    }
```

Den har ikke tilgang til     featureToggleService, eller user - og vet ikke hvilken toggle skal sjekkes

Tanken var at filterForEnheter tar

fra service: featureToggleService, toggle - denne forsvinner når vi gjør featurene permanent
fra Kontekst: user

samt en trailing block som er filter function (fordi sak, behandling og oppgaver filtrerer på litt forskjellige vis - hvor er felt for eksempel).

2023-04-17 10:34 UTC, chrissearle commented on apps/etterlatte-behandling/src/main/kotlin/sak/SakService.kt
> +fun <T : Sak> List<T>.filterSakerForEnheter(
Klipp/lim fra behandling - kan godt være bare Sak

2023-04-17 10:35 UTC, chrissearle commented on apps/etterlatte-behandling/src/main/kotlin/behandling/foerstegangsbehandling/FoerstegangsbehandlingService.kt
> +                    listOf(it).filterSakerForEnheter(featureToggleService, Kontekst.get().AppUser).firstOrNull()
Per nå

Ville ha sikkerhet på plass i tilfelle noen senere kaller den fra et annet sted.

Har hatt samme tilnærming i alle services - service skal ikke anta at det kalles bare fra trygge steder.

2023-04-17 10:38 UTC, chrissearle commented on apps/etterlatte-behandling/src/main/kotlin/behandling/GenerellBehandlingService.kt
> +    private fun Behandling?.sjekkEnhet() = this?.let { behandling ->
Stemmer nok. I de andre service klassene så var tilsvarende brukt mer ofte - så var konsistent å ha eget funksjon men kan godt inline den her.

2023-04-17 13:08 UTC, Watercolours approved these changes
Siden det meste forsvinner når dette ikke lenger er bak en feature toggle (ref. EY-2040), får det bare gå gjennom i denne runden.

2023-04-17 13:12 UTC, merged