EY-1979 og EY-1981: Migrering for beregning og vedtak
navikt/pensjon-etterlatte-saksbehandling pull request #1386
Opened 2023-05-09 13:21 UTC by madsop-nav

2023-05-10 11:35 UTC, EspenSchei commented on apps/etterlatte-beregning-kafka/src/main/kotlin/no/nav/etterlatte/beregningkafka/MigreringHendelser.kt
> +                val beregning = beregningService.beregn(behandlingId)
Her kommer det nok til å krasje på at vi ikke har beregningsgrunnlag?
Vi trenger å populere grunnlaget først med hvilke søsken som skal tas med i beregningen

2023-05-10 11:40 UTC, EspenSchei requested changes
Ref. kommentaren om at vi ikke får inn grunnlag, så tenker jeg vi bør få det inn med en gang.

2023-05-10 11:40 UTC, EspenSchei commented on apps/etterlatte-beregning-kafka/src/main/kotlin/no/nav/etterlatte/beregningkafka/BeregningService.kt
> +        beregningApp.post("$url/api/beregning/$omregningsId") {}
Siden vi først endrer her, kan vi også fjerne klammeparantesene? :D

2023-05-10 11:40 UTC, EspenSchei commented on apps/etterlatte-beregning-kafka/src/main/kotlin/no/nav/etterlatte/beregningkafka/BeregningService.kt
> +    fun beregn(behandlingId: UUID): BeregningDTO = runBlocking {
Burde vi standardisert her i stedet, siden den kaller akkurat det samme url-en som `opprettOmregning `, men returnerer DTO-en?

2023-05-12 10:28 UTC, madsop-nav commented on apps/etterlatte-beregning-kafka/src/main/kotlin/no/nav/etterlatte/beregningkafka/MigreringHendelser.kt
> +                val beregning = beregningService.beregn(behandlingId)
> Her kommer det nok til å krasje på at vi ikke har beregningsgrunnlag? Vi trenger å populere grunnlaget først med hvilke søsken som skal tas med i beregningen

Ja, a la det Øyvind viste på demo i dag? Litt usikker på korleis vi skal løyse det 🤔

2023-05-12 16:58 UTC, madsop-nav commented on apps/etterlatte-beregning-kafka/src/main/kotlin/no/nav/etterlatte/beregningkafka/MigreringHendelser.kt
> +                val beregning = beregningService.beregn(behandlingId)
Puh, måtte litt røsking til, men no trur eg vi har eit grunnlag.

2023-05-23 13:11 UTC, madsop-nav commented
Lukkar denne til fordel for ein sekvens av nye, meir oppdelte PR-ar

2023-05-23 13:11 UTC, closed without merging