EY-2188 - behandling kan markeres med utenlandstilsnitt - frontend
navikt/pensjon-etterlatte-saksbehandling pull request #1438
Opened 2023-05-23 08:18 UTC by chrissearle

Venter input fra EY-2186 om design, tekster, lov lenker osv.

2023-05-24 10:23 UTC, emilps commented on apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/utenlandstilsnitt/UtenlandstilsnittVurdering.tsx
> +            <div>
Denne kan nok fjernes hvis den ikke har noe styling tilknyttet

2023-05-24 10:24 UTC, emilps commented on apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/utenlandstilsnitt/UtenlandstilsnittVurdering.tsx
> +      <div>
VurderingsbokWrapper er en div, så du trenger ikke å ha en div inni

2023-05-24 10:30 UTC, chrissearle commented on apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/utenlandstilsnitt/UtenlandstilsnittVurdering.tsx
> +      <div>
Samme som over - var en gruppering i den jeg baserte det på som er borte her - skal fjernes

2023-05-24 11:34 UTC, sebassonav commented on apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/utenlandstilsnitt/Utenlandstilsnitt.tsx
> +const statusIkon = (utenlandstilsnitt: IUtenlandstilsnitt | undefined) => {
Kanskje typen `IUtenlandstilsnitt` skal ha en type der den er enten det `IUtenlandstilsnitt` er i dag og en type med `IUtenlandstilsnitt | undefined` som kan brukes rundt omkring

2023-05-24 11:36 UTC, sebassonav commented on apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/utenlandstilsnitt/Utenlandstilsnitt.tsx
> +  const [vurder, setVurder] = useState(behandling.utenlandstilsnitt !== null)
Kan den være `null` i tillegg til `undefined`? 🤔

2023-05-24 11:37 UTC, sebassonav commented on apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/utenlandstilsnitt/Utenlandstilsnitt.tsx
> +  const [vurder, setVurder] = useState(behandling.utenlandstilsnitt !== null)
nitpick: `setVurdert`

2023-05-24 11:37 UTC, sebassonav commented on apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/utenlandstilsnitt/Utenlandstilsnitt.tsx
> +  const [vurder, setVurder] = useState(behandling.utenlandstilsnitt !== null)
og `vurdert`

2023-05-24 12:04 UTC, sebassonav approved these changes

2023-05-24 12:05 UTC, sebassonav commented on apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/utenlandstilsnitt/UtenlandstilsnittVurdering.tsx
> +        <Undertekst gray={false}>Hvilken type sak er dette?</Undertekst>
Finnes attributtet `gray` her?

2023-05-24 12:06 UTC, sebassonav commented on apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/utenlandstilsnitt/UtenlandstilsnittVurdering.tsx
> +            value={svar || ''}
Burde svar være `Utenlandstilsnitt | ''` i useStaten?

2023-05-24 12:07 UTC, sebassonav requested changes

2023-05-24 12:07 UTC, sebassonav commented on apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/utenlandstilsnitt/UtenlandstilsnittVurdering.tsx
> +      return setUtenlandstilsnitt({ behandlingId, begrunnelse, svar }, (response) => {
Burde vi håndtere feilsituasjonene her og?

2023-05-24 12:32 UTC, chrissearle commented on apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/utenlandstilsnitt/UtenlandstilsnittVurdering.tsx
> +      return setUtenlandstilsnitt({ behandlingId, begrunnelse, svar }, (response) => {
Mulig. Har gjort det samme her som virkningstidspunkt - så det er kanskje et litt større teknisk gjeld sak enn bare den ene.

2023-05-24 13:20 UTC, chrissearle commented on apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/utenlandstilsnitt/Utenlandstilsnitt.tsx
> +  const [vurder, setVurder] = useState(behandling.utenlandstilsnitt !== null)
Klipp/lim - endret

2023-05-24 13:52 UTC, sebassonav approved these changes

2023-05-24 13:52 UTC, sebassonav commented on apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/utenlandstilsnitt/UtenlandstilsnittVurdering.tsx
> +        {isFailure(setUtenlandstilsnittStatus) && <ApiErrorAlert>Kunne ikke lagre utlandstilknytning</ApiErrorAlert>}
Kan de prøve igjen?

2023-05-26 05:43 UTC, chrissearle commented on apps/etterlatte-saksbehandling-ui/client/src/components/behandling/soeknadsoversikt/soeknadoversikt/utenlandstilsnitt/UtenlandstilsnittVurdering.tsx
> +        {isFailure(setUtenlandstilsnittStatus) && <ApiErrorAlert>Kunne ikke lagre utlandstilknytning</ApiErrorAlert>}
Vi trenger å ta en gjennomgang av lagring på alle disse søknadsoversikt svar - de fleste ignorerer det helt.

Tenker vi la denne her stå siden det er bedre i det minst å vise at noe har skjedd - så kan vi få alle søknadsoversikt tingene til å feilhåndtere på en konsistent måte på https://jira.adeo.no/browse/EY-2235

2023-05-26 05:44 UTC, merged