EY-1979 del 1: Tilrettelegging
navikt/pensjon-etterlatte-saksbehandling pull request #1439
Opened 2023-05-23 10:50 UTC by madsop-nav

Legg til rette for å i neste runde kunne få på plass migreringsstøtte også for beregning og vedtak

2023-05-23 12:19 UTC, sebassonav approved these changes

2023-05-23 12:20 UTC, sebassonav requested changes

2023-05-23 12:20 UTC, sebassonav commented on apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/HentSoeskenjustering.kt
> +fun Grunnlagsdata<JsonNode>.hentSoeskenjustering() =
Dette er en duplikat av den som ligger i `Grunnlagsdata`.

2023-05-23 12:22 UTC, madsop-nav commented on apps/etterlatte-beregning/src/main/kotlin/beregning/grunnlag/HentSoeskenjustering.kt
> +fun Grunnlagsdata<JsonNode>.hentSoeskenjustering() =
Neida, den er flytta ut derifrå 😄

2023-05-23 17:22 UTC, EspenSchei approved these changes

2023-05-24 06:46 UTC, henrikg approved these changes
👍

2023-05-24 20:50 UTC, merged