Fix for å ignorere sivilstandsendringer på søsken
navikt/pensjon-etterlatte-saksbehandling pull request #1767
Opened 2023-07-17 13:46 UTC by jorgesti

Det blir kanskje ikke helt pent som en enkel fix. Må evt skrive om mer for å få det penere

2023-07-17 14:07 UTC, madsop-nav approved these changes

2023-07-18 08:00 UTC, sebassonav requested changes

2023-07-18 08:00 UTC, sebassonav commented on apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseService.kt
> +                    SamsvarMellomKildeOgGrunnlag.Sivilstand(null,null,true)
Jeg tror dette blir litt rart.
Kanskje gjøre slik?
```
            GrunnlagsendringsType.INSTITUSJONSOPPHOLD ->
                throw IllegalStateException("Denne hendelsen skal gå rett til oppgavelisten og aldri komme hit")
```

Også filtrere ut denne hendelse fra pdl-hendelser appen?
Evt sette denne til forkastet, se `forkastHendelse()`

2023-07-18 08:23 UTC, jorgesti commented on apps/etterlatte-behandling/src/main/kotlin/grunnlagsendring/GrunnlagsendringshendelseService.kt
> +                    SamsvarMellomKildeOgGrunnlag.Sivilstand(null,null,true)
Men det vil vel ikke fikse 'original problemet' vel? Dvs at det kastes en haug med Error meldinger? Men filtrering i pdl-hendelser hørtes lurt ut

2023-07-18 09:33 UTC, jorgesti commented
gjør det på en annen måte

2023-07-19 11:11 UTC, jorgesti commented
Etter diskusjon, fant vi ut at dette var beste måten å løse det på nå

2023-07-19 11:14 UTC, sebassonav approved these changes

2023-07-19 11:17 UTC, merged