EY-2469-Opprette oppgave for attestant
navikt/pensjon-etterlatte-saksbehandling pull request #1801
Opened 2023-07-20 11:34 UTC by jorgesti

@sebassonav som diskutert: skal se på å flytte logikken til fattVedtak med egne API-kall

2023-07-20 12:05 UTC, sebassonav requested changes

2023-07-20 12:05 UTC, sebassonav commented on apps/etterlatte-behandling/src/main/kotlin/behandling/BehandlingStatusService.kt
> +            oppgaveService.opprettNyOppgaveMedSakOgReferanse(
Tror vi må se på dette som en egen ting og ikke blande det inn i statusoppdateringene men heller gjøre et separat kall for dette.

2023-07-21 10:44 UTC, sebassonav commented on apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/klienter/BehandlingKlient.kt
> +    suspend fun opprettOppgave(referanse: String?,sakId: Long, brukerTokenInfo: BrukerTokenInfo,oppgaveType: OppgaveType ): Boolean
nitpick: Men har du ikke på ktlint til formatering?

2023-07-21 10:56 UTC, sebassonav commented on apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/klienter/BehandlingKlient.kt
> +                referanse = "tjoho", sakId = sakId, oppgaveType =  oppgaveType
referanse skal vel være behandlingsiden

2023-07-21 10:56 UTC, sebassonav commented on apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/klienter/BehandlingKlient.kt
> +enum class OppgaveType {
Hadde vært nice om vi kunne brukt samme typen som i behandling her så vi ikke får noen overraskelser

2023-07-21 10:56 UTC, sebassonav commented on apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/klienter/BehandlingKlient.kt
> +data class OpprettNyOppgaveRequest(
Det samme gjelder her, denne og blir duplisert mellom appene.

2023-07-21 10:56 UTC, sebassonav commented on apps/etterlatte-behandling/src/main/kotlin/oppgaveny/OppgaveNy.kt
> +    ATTESTERING,
Denne må også legges til i frontend

2023-07-21 10:56 UTC, sebassonav commented on apps/etterlatte-behandling/src/main/kotlin/oppgaveny/OppgaveServiceNy.kt
> +    fun opprettNyOppgaveMedSakOgReferanse(referanse: String, sakId: Long, oppgaveType: OppgaveType, saksbehandler: String? = null): OppgaveNy {
Siden ingen av de andre som bruker denne sender med saksbehandler så foreslår jeg at vi bare lager en ny med denne signaturen som gjør det samme.

2023-07-21 10:57 UTC, sebassonav commented on apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingService.kt
> +        behandlingKlient.opprettOppgave(
Ikke krise men denne og kallet over kan gjøres samtidig i et coroutineScope

2023-07-21 11:02 UTC, jorgesti commented on apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/klienter/BehandlingKlient.kt
> +    suspend fun opprettOppgave(referanse: String?,sakId: Long, brukerTokenInfo: BrukerTokenInfo,oppgaveType: OppgaveType ): Boolean
nå så :)

2023-07-21 11:03 UTC, jorgesti commented on apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/klienter/BehandlingKlient.kt
> +                referanse = "tjoho", sakId = sakId, oppgaveType =  oppgaveType
glemte å rette den ja. fiksa nå.

2023-07-21 11:08 UTC, jorgesti commented on apps/etterlatte-behandling/src/main/kotlin/oppgaveny/OppgaveServiceNy.kt
> +    fun opprettNyOppgaveMedSakOgReferanse(referanse: String, sakId: Long, oppgaveType: OppgaveType, saksbehandler: String? = null): OppgaveNy {
fiksa

2023-07-21 11:11 UTC, jorgesti commented on apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/VedtaksvurderingService.kt
> +        behandlingKlient.opprettOppgave(
fiksa

2023-07-21 11:20 UTC, jorgesti commented on apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/klienter/BehandlingKlient.kt
> +enum class OppgaveType {
fiksa

2023-07-21 11:20 UTC, jorgesti commented on apps/etterlatte-vedtaksvurdering/src/main/kotlin/vedtaksvurdering/klienter/BehandlingKlient.kt
> +data class OpprettNyOppgaveRequest(
fiksa

2023-07-21 11:26 UTC, jorgesti commented on apps/etterlatte-behandling/src/main/kotlin/oppgaveny/OppgaveNy.kt
> +    ATTESTERING,
lagt til på oppgavetypefilterkeys, må den inn andre plasser også?

2023-07-21 12:12 UTC, closed without merging