Gosys URL i frontend - benytte Vite modes
navikt/pensjon-etterlatte-saksbehandling pull request #1978
Opened 2023-08-15 07:31 UTC by ingleivj

Så, ettersom klientkoden er statisk så prosesseres dette av Vite under bygg - og da er ikke GOSYS_URL tilgjengelig. Om den var det (i miljøet til Github Actions), så ville det uansett bare vært èn, m.a.o. ingen differensiering av prod vs dev. Så iht dok, så må man benytte .env-filer for dette formålet, og lage _én artifakt pr ønsket miljø_.... 

https://vitejs.dev/guide/env-and-mode.html

Lokalt så fungerer det uten env-filer ettersom man setter miljøvariabelen f.eks. i terminalen og så kjører vite - for da er jo variabelen tilgjengelig for bygget/serveren.

2023-08-15 07:33 UTC, ingleivj commented on .github/workflows/app-etterlatte-saksbehandling-ui.yaml
>            tag: ${{ env.GITHUB_REF_SLUG }}
får ikke til å sette environment som en del av versjon/tag, støttes ikke av actionen hva jeg ser.

2023-08-15 07:33 UTC, sebassonav commented on apps/etterlatte-saksbehandling-ui/client/package.json
> +    "build:dev": "tsc && eslint src --ext .ts,.tsx && vite build --mode development",
Denne ganske nice egentlig

2023-08-15 07:35 UTC, sebassonav approved these changes

2023-08-15 07:38 UTC, Watercolours reviewed
Ikke fan av denne løsningen. Da må vi plutselig forholde oss til env-filer i tillegg. Litt rart at du fikk commite ettersom jeg har lagt til `**.env**` i .gitignore. 

Sett heller opp et endepunkt i frackend som henter verdien fra nais.yaml og kall på det endepunktet fra frontend.

2023-08-15 07:38 UTC, Watercolours requested changes
Ref. kommentar

2023-08-15 07:40 UTC, ingleivj commented
> Ikke fan av denne løsningen. Da må vi plutselig forholde oss til env-filer i tillegg. Litt rart at du fikk commite ettersom jeg har lagt til `**.env**` i .gitignore.

Spesifikk add så går det helt greit.

> Sett heller opp et endepunkt i frackend som henter verdien fra nais.yaml og kall på det endepunktet fra frontend.

Har vurdert det - men hvorfor ikke forholde seg til slik Vite er designet?

2023-08-15 07:46 UTC, Watercolours commented
Problemet er at vi ikke egentlig kjører Vite når vi bygger prosjektet. Da kjører vi en node-app som peker på et statisk prosjekt. Om vi kjørte Vite serverside hadde jeg vært helt med på den. 

I tillegg blir det bare mer rot å innføre enda en config-fil man må forholde seg til. For ikke å nevne at _alt_ annet av API-kall går gjennom frackend. 

Men det er nå min mening. Hva tenker du, @sebassonav? Ettersom du har godkjent synes du kanskje ikke det gjør noe?

2023-08-15 07:52 UTC, Watercolours commented
Litt dårlig formulert fra min side. Vite kjører ikke appen _etter_ det er bygget.

2023-08-15 08:16 UTC, sebassonav commented on apps/etterlatte-saksbehandling-ui/client/vite.config.ts
> -    define: {
Hvis slik så kan du fjerne `env` ovenfor og import av `loadEnv`.

2023-08-15 08:23 UTC, sebassonav commented
Ellers så kunne man hatt begge urlene lagret i en js fil og kun sjekket på `import.meta.env.MODE` som nå blir satt så slipper man env filene og den nye spesial env variabelen for gosysurler.

2023-08-15 10:46 UTC, Watercolours commented
Tja... med tanke på hvor lite som skal til i dagens løsning for at dette skal fungere, synes jeg dette blir en unødvendig kompleks løsning. Holder med noe á la dette: 

```
index.ts

app.use('/api/gosys', proxy(ApiConfig.gosys.url))
```

```
config.ts

gosys: {
     url: requireEnvValue('GOSYS_API_URL'),
},
```

Så slipper vi ytterligere kompleksitet i config-filer 😄

--- 

Ang. to ulike docker images for å støtte dev og prod mode, synes jeg det er en ganske god idé ettersom det vil gi støtte for DevTools i dev. Eneste minuset her er at dette vil aktivere `StrictMode` i dev som er litt uheldig siden flere av appene oppleves som ustabile ved doble API-kall. Mulig det finnes en finurlig vei rundt dette. React dok sier at StrictMode kun skal være aktiv dersom `env == 'development'`, men lokalt fremstår det som at StrictMode aktiveres dersom `env != 'production'`.

2023-08-15 11:21 UTC, sebassonav commented
@Watercolours `StrictMode` gjør vel kun doble API kall på `GET` kall som er skjer ved lasting av js-bundelen og ikke hvis det er bruker initiert. Da er det vel ikke et like stort problem?

2023-08-15 11:46 UTC, Watercolours commented
Trigger dobbel `useEffect` som på de fleste sider trigger et API-kall. Flere av appene er satt opp slik at de ved GET 404/204 kjører en POST. Så det er flere steder hvor man lokalt får 2x POST pga. Strict. Vi har så vidt jeg vet sikret mot idempotens, men det skaper allikevel litt støy siden det flere steder "kræsjer" for å hindre doble inserts, osv.

2023-08-15 12:01 UTC, sebassonav commented
Kan vi ikke bare fjerne strictmode i appen vår da, hva bruker vi det til egentlig?

2023-08-15 12:08 UTC, Watercolours commented
Strictmode er nyttig for å idiotsikre frontenden litt. Avdekker fort rendering- og/eller idempotensproblemer, m.m. 
Å skru det av er litt som å skru av tester fordi det tar for lang tid å bygge... 🤷 

https://react.dev/reference/react/StrictMode

2023-08-15 12:58 UTC, oyvindsh commented
> @Watercolours jeg er uenig med deg :) Vi kan jo fint kjøre med det lokalt men ikke i dev/prod..

https://react.dev/reference/react/StrictMode

`StrictMode`-sjekkene kjører ikke i dev / prod, kun i lokal kjøring

2023-08-15 13:04 UTC, Watercolours commented
@oyvindsh: Det kjører ikke i dev nå siden byggimaget setter `NODE_ENV=production`. Ved lokal utvikling defaulter den til `development`. Mulig vi kan omgå strict i dev ved å bygge et image med f.eks. `NODE_ENV=staging`, men det fungerte ikke da jeg testet kjapt lokalt tidligere i dag.

2023-08-15 13:34 UTC, madsop-nav commented
Er vi ikkje her inne i _kva er den minst dårlege løysinga_-land?

Min take her er at eg er skeptisk til at vi skal ha forskjellige images i dev og prod. Ein av dei store styrkane ved containers er nettopp at dev og prod (og alle andre miljø) kan ha akkurat samme kode og samme image. (Og ja, det irriterer meg at det er dette Vite legg opp til. https://github.com/vitejs/vite/issues/10059 er ein open issue i Vite som går på akkurat det her.).

Synes også det er litt klønete at frontend skal spørre frackend, men trur eg synes det er eit mindre onde. Alternativt kan vi køyre noko a la det @sebassonav foreslo under? Alternativt at vi har eit endepunkt i frackend som returnerer miljø, og så kan alt anna ligge i konfig-filer i frontenden?

> Ellers så kunne man hatt begge urlene lagret i en js fil og kun sjekket på import.meta.env.MODE som nå blir satt så slipper man env filene og den nye spesial env variabelen for gosysurler.

2023-08-17 08:15 UTC, ingleivj commented
Er ikke noen fan av separate images selv heller, men registrerer at det er ganske vanlig å gjøre det på den måten.

Uansett, har sett på det å hente fra frackend (_mode_-løsningen krever vel også separate images). Nå er jeg ikke spesielt bevandret i react-verdenen, men det fremstår for meg som at løsningen for å unngå å hente inn flere ganger er å sette opp en Context på et høyt nivå, som man så wrapper hele oppgavelista-treet i? Da basically på App-nivå. Tar gjerne i mot innspill :)

2023-08-17 10:02 UTC, ingleivj commented
Erstattet av #1978

2023-08-17 10:02 UTC, closed without merging