EY-2421 - tillatt ANNEN i prod
navikt/pensjon-etterlatte-saksbehandling pull request #2248
Opened 2023-09-26 08:28 UTC by chrissearle

2023-09-26 08:29 UTC, madsop-nav commented
Oi, når eg tenkjer meg om trur eg ikkje endringsmalen med redigering er godkjent/klar til prod.

2023-09-26 08:30 UTC, madsop-nav requested changes
Trur ikkje hovudmalen er godkjent/klar enno, det må på plass først.

2023-09-26 08:36 UTC, chrissearle commented
> Trur ikkje hovudmalen er godkjent/klar enno, det må på plass først.

OK.

Men - det er også `pensjon-etterlatte.opprett-manuell-revurdering` som er kun på i dev - som er vel også relatert?

2023-09-26 08:44 UTC, madsop-nav commented
> > Trur ikkje hovudmalen er godkjent/klar enno, det må på plass først.
> 
> OK.
> 
> Men - det er også `pensjon-etterlatte.opprett-manuell-revurdering` som er kun på i dev - som er vel også relatert?

Nei, det ser ut til å vera det å kunne opprette revurdering, som eg trur er uproblematisk. Søskenjustering-malen er spesiell og er ute i prod, så det er vel primært for den.

2024-02-16 10:15 UTC, henrikg commented
Lukker denne da jeg tenker vi kan ta dette opp når det blir aktuelt å legge "ANNEN" ut i produksjon. PR nå tror jeg vi ønsker å holde denne unna prod for å kunne identifisere ulike saker vi ikke håndterer på en god måte.

2024-02-16 10:15 UTC, closed without merging