Legger til støtte i backend for å støtte nye vilkår
navikt/pensjon-etterlatte-saksbehandling pull request #2473
Opened 2023-10-20 10:59 UTC by EspenSchei

- Legger til støtte for å kunne slette eksisterende vilkårsvurdering
- Legger til støtte for å kunne opprette ny vilkårvurdering når man revurderer uten å kopiere fra forrige.

EY-2826

2023-10-20 13:43 UTC, henrikg approved these changes

2023-10-20 14:21 UTC, sebassonav commented on apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/VilkaarsvurderingService.kt
> +    fun slettVilkaarsvurdering(
Hvorfor bruker vi `runBlocking` her?
```suggestion
    suspend fun slettVilkaarsvurdering(
        behandlingId: UUID,
        brukerTokenInfo: BrukerTokenInfo,
    ) = vilkaarsvurderingRepository.slettVilkaarvurdering(behandlingId).also {
        behandlingKlient.settBehandlingStatusOpprettet(behandlingId, brukerTokenInfo, true)
    }
```

2023-10-20 14:24 UTC, sebassonav commented on apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/VilkaarsvurderingService.kt
> +    fun slettVilkaarsvurdering(
Nitpick, also er ikke nødvendig
```suggestion
    suspend fun slettVilkaarsvurdering(
        behandlingId: UUID,
        brukerTokenInfo: BrukerTokenInfo,
    ) {
        vilkaarsvurderingRepository.slettVilkaarvurdering(behandlingId)
        behandlingKlient.settBehandlingStatusOpprettet(behandlingId, brukerTokenInfo, true)
    }
```

2023-10-20 14:27 UTC, sebassonav commented on apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/VilkaarsvurderingService.kt
> +        runBlocking { behandlingKlient.settBehandlingStatusOpprettet(behandlingId, brukerTokenInfo, true) }
On a side note: Hva hvis `settBehandlingStatusOpprettet` feiler? Jeg og Øyvind lagde noe intransaction wrapper på det i vedtaksvurderingsservice.

2023-10-20 14:31 UTC, sebassonav requested changes

2023-10-20 14:31 UTC, sebassonav commented on apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/VilkaarsvurderingRoutes.kt
> +                } catch (e: BehandlingstilstandException) {
`BehandlingstilstandException` kan aldri forekomme her?

2023-10-23 06:45 UTC, EspenSchei commented on apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/VilkaarsvurderingRoutes.kt
> +                } catch (e: BehandlingstilstandException) {
Hmm, nei. Men det burde det gjøre. Skal fikse det.

2023-10-23 06:53 UTC, EspenSchei commented on apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/VilkaarsvurderingService.kt
> +        runBlocking { behandlingKlient.settBehandlingStatusOpprettet(behandlingId, brukerTokenInfo, true) }
Opprettet en egen Jira på denne siden det gjelder flere her: [EY-2958](https://jira.adeo.no/browse/EY-2958)

2023-10-23 07:14 UTC, EspenSchei commented on apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/VilkaarsvurderingRoutes.kt
> +                } catch (e: BehandlingstilstandException) {
[6ac27e4](https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/2473/commits/6ac27e403cd5a4b96c4c12d344cc5c75cc664930)

2023-10-23 07:15 UTC, EspenSchei commented on apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/VilkaarsvurderingService.kt
> +    fun slettVilkaarsvurdering(
[6ac27e4](https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/2473/commits/6ac27e403cd5a4b96c4c12d344cc5c75cc664930)

2023-10-23 09:17 UTC, sebassonav approved these changes

2023-10-23 12:01 UTC, merged