Ey 2949 rediger behandling advarsel om utdatert brev
navikt/pensjon-etterlatte-saksbehandling pull request #2678
Opened 2023-11-09 20:29 UTC by henrikg

2023-11-10 07:35 UTC, henrikg commented on apps/etterlatte-saksbehandling-ui/client/src/store/reducers/BehandlingReducer.ts
> +export const oppdaterBehandling = createAction<IDetaljertBehandling>('behandling/oppdater')
Ønsker å oppdatere behandling, men wipe feks vilkårsvurdering og andre ting rundt

2023-11-10 07:36 UTC, henrikg commented on apps/etterlatte-saksbehandling-ui/client/src/components/behandling/brev/RedigerbartBrev.tsx
> +  lukkAdvarselBehandlingEndret?: () => void
Dette føles en smule hacky - har vi noen lurere måter å gjøre dette på med react?

2023-11-10 09:17 UTC, sebassonav requested changes

2023-11-10 09:17 UTC, sebassonav commented on apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/model/BrevModel.kt
> +fun main() {
🕐

2023-11-10 09:19 UTC, sebassonav commented on apps/etterlatte-brev-api/src/main/kotlin/no/nav/etterlatte/brev/db/BrevRepository.kt
> +                h.opprettet as hendelse_opprettet, m.*
Er det ikke forskjell på når brevet først ble opprettet og når det sist ble redigert?

2023-11-10 12:37 UTC, Bjodn approved these changes

2023-11-17 08:23 UTC, sebassonav approved these changes

2023-11-19 21:06 UTC, merged