Logger adressedata ved henting fra Persondata
navikt/pensjon-etterlatte-saksbehandling pull request #3114
Opened 2023-12-08 12:25 UTC by tvsignal

2023-12-08 12:29 UTC, madsop-nav approved these changes
Kan vera nyttig, så får vi reversere det når vi er gjennom

2023-12-08 12:29 UTC, madsop-nav commented on apps/etterlatte-grunnlag/src/main/kotlin/klienter/PersondataKlient.kt
> +                sikkerLogg.warn(
Lurer på om det er betre her med info eller kanskje helst debug?

2023-12-11 13:24 UTC, madsop-nav commented
Trur, ref nyaste kommentarar frå Skatt/PDL, at ikkje denne blir relevant lell, så trur vi skal avvente før vi eventuelt mergar denne.

2023-12-14 06:26 UTC, sebassonav approved these changes

2023-12-15 07:30 UTC, madsop-nav requested changes
Trur ikkje vi lenger treng denne.

2023-12-15 10:57 UTC, closed without merging