Rydde iht naiskonsollet - første runde
navikt/pensjon-etterlatte-saksbehandling pull request #3145
Opened 2023-12-11 18:51 UTC by madsop-nav

Starta på https://console.nav.cloud.nais.io/team/etterlatte/applications og kikka på dei første med gul varseltrekant. Det kjem fleire PR-ar i samme gate.

2023-12-11 19:16 UTC, Watercolours requested changes
Må ikke fjerne `etterlatte-saksbehandling-ui-lokal`. Trenger de for at lokal kjøring mot dev-gcp skal fungere

2023-12-12 07:49 UTC, madsop-nav commented
> Må ikke fjerne `etterlatte-saksbehandling-ui-lokal`. Trenger de for at lokal kjøring mot dev-gcp skal fungere

Einig, men har berre fjerna dei frå prod-gcp?

2023-12-12 08:35 UTC, Watercolours commented
> > Må ikke fjerne `etterlatte-saksbehandling-ui-lokal`. Trenger de for at lokal kjøring mot dev-gcp skal fungere
> 
> Einig, men har berre fjerna dei frå prod-gcp?

Visst pokker er det dét! Beklager, jeg var litt kjapp der og tok det for gitt at det var `dev-gcp`. 🤦 
Burde kanskje slenge på en kommentar på de i `dev-gcp` for å unngå at folk kopierer de til prod.

2023-12-12 08:35 UTC, Watercolours approved these changes

2023-12-12 09:36 UTC, merged