Ey 1315 fjern endepunkt
navikt/pensjon-etterlatte-saksbehandling pull request #362
Opened 2022-12-13 12:22 UTC by simejo

Fjernet et ubrukt endepunkt i VedtakbehandlingRoute `get("hentvedtak/{sakId}/{behandlingId}")`

Ryddet samtidig opp i gjenbrukt kode (`withBehandlingId` og `navIdent`)

2022-12-13 12:45 UTC, EspenSchei requested changes

2022-12-13 12:45 UTC, EspenSchei commented on libs/common/build.gradle.kts
> +    implementation(NavFelles.TokenValidationKtor2)
Vi ønsker vel ikke å dra inn ´Ktor´ i common?

2022-12-13 12:45 UTC, EspenSchei commented on libs/common/src/main/kotlin/RouteUtils.kt
> +package no.nav.etterlatte.libs.common
Noe av denne funksjonaliteten finnes allerede i common biblioteket Henrik har laget tidligere: `etterlatte-ktor`. Burde vel heller benytte det, og evt. legge til `withBehandlingId` funksjonen der :)

2022-12-13 13:00 UTC, simejo commented on libs/common/build.gradle.kts
> +    implementation(NavFelles.TokenValidationKtor2)
Flytter til etterlatte-ktor 👍

2022-12-13 13:29 UTC, sebassonav approved these changes
lgtm

2022-12-13 13:33 UTC, EspenSchei approved these changes

2022-12-13 13:33 UTC, EspenSchei commented on libs/etterlatte-ktor/src/main/kotlin/RouteUtils.kt
> +val ApplicationCall.navIdent: String get() = principal<TokenValidationContextPrincipal>()!!
Ser forresten at vi har noe lignende i `TokenUtils.kt`:
```
inline val PipelineContext<*, ApplicationCall>.saksbehandler: String
    get() = requireNotNull(
        call.principal<TokenValidationContextPrincipal>()
            ?.context?.getJwtToken("azure")
            ?.jwtTokenClaims?.getStringClaim("NAVident")
    )
```

2022-12-14 14:05 UTC, simejo commented on libs/etterlatte-ktor/src/main/kotlin/RouteUtils.kt
> +val ApplicationCall.navIdent: String get() = principal<TokenValidationContextPrincipal>()!!
Aha, bytta ut med den 👍

2022-12-14 14:19 UTC, merged