Legger til sikkerlogg ved kall til grunnlag.
navikt/pensjon-etterlatte-saksbehandling pull request #488
Opened 2023-01-19 13:18 UTC by EspenSchei

EY-1602

2023-01-19 13:37 UTC, henrikg approved these changes

2023-01-20 10:38 UTC, sebassonav commented on apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/grunnlag/GrunnlagKlient.kt
> +                        sikkerLogg.error("Feil under deserialisering av grunnlag", lastError())
Skal vel kun bruke sikkerlogg hvis dette blir en suksess? Du får jo ingen data hvis  statusen er failure 🧇

2023-01-20 10:38 UTC, sebassonav requested changes

2023-01-20 10:38 UTC, sebassonav commented on apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/grunnlag/GrunnlagKlient.kt
> +                        sikkerLogg.error("Feil under deserialisering av grunnlag", lastError())
Skal vel kun bruke sikkerlogg hvis dette blir en suksess? Du får jo ingen data hvis statusen er failure 🧇

2023-01-20 10:45 UTC, sebassonav approved these changes

2023-01-23 10:52 UTC, EspenSchei commented on apps/etterlatte-vilkaarsvurdering/src/main/kotlin/vilkaarsvurdering/grunnlag/GrunnlagKlient.kt
> +                    throw exceptions.last()
Lager en egen PR på et forsøk her.

2023-01-23 10:52 UTC, closed without merging