EY-4011: Legg til støtte for uføre og aap på barnepensjon
navikt/pensjon-etterlatte-saksbehandling pull request #5123
Opened 2024-06-13 08:39 UTC by emilps

2024-06-13 08:41 UTC, oyvindsh approved these changes

2024-06-13 08:43 UTC, sebassonav approved these changes

2024-06-13 08:46 UTC, sebassonav commented
Noe som brekker her gitt

2024-06-13 08:46 UTC, sebassonav requested changes
fiks tester

2024-06-14 07:46 UTC, sebassonav approved these changes

2024-06-14 07:50 UTC, merged