Forbedre feilmelding ved manglende tilgang
navikt/pensjon-etterlatte-saksbehandling pull request #6161
Opened 2024-10-31 07:45 UTC by Watercolours

Forslag til forbedring på feil som kastes og feilmelding som vises til saksbehandler. 

P.t. må vi bruke masse tid på å debugge hver gang de ikke har tilgang siden de får en veldig misvisende "404 Ressurs ikke funnet". Dette vil spare både oss og saksbehandler mye tid på sikt..

2024-10-31 09:06 UTC, henrikg approved these changes

2024-10-31 11:10 UTC, sebassonav commented
"Masse tid" , kan du gi et eksempel som er veldig vanskelig å debugge pga av dette ?

2024-10-31 11:32 UTC, sebassonav requested changes

2024-10-31 11:32 UTC, sebassonav commented on libs/etterlatte-ktor/src/main/kotlin/route/RouteUtils.kt
> -                throw GenerellIkkeFunnetException()
Dette må gjøres i Tilgangsstyring.kt wrapperen også

2024-11-07 07:09 UTC, Watercolours commented
Ved nærmere undersøkelse burde vi _muligens_ skille på manglende tilgang til enhet og gradert bruker. Lukker denne og tar opp tråden igjen på et senere tidspunkt når jeg har litt ledig tid.

2024-11-07 07:09 UTC, closed without merging